kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: nginx-daemonsets
  namespace: ngnix  
spec: 
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name : nginx-dae-pod
      labels:
        app: nginx 
    spec:
      containers: 
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80    
